sudo: required
dist: trusty
language: node_js
node_js:
  - "12.0"
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - shawmakesmusic@gmail.com
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm i -g travis-ci-cloudfront-invalidation
  - npm i -g react-deploy-cli
  - CI=false npm run build #use your build script
before_script:
  - export RELEASE_HEAD=$(git rev-parse --short HEAD | cut -c1-7)  
  - export RELEASE_HEAD_LONG=$(git rev-parse HEAD)  
  - export CI=true
script: 'true'
after_deploy:
- travis-ci-cloudfront-invalidation -a $ACCESS_KEY -s $SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master,stage'  
deploy:
  skip_cleanup: true
  provider: script
  script: react-deploy deploy $TRAVIS_BRANCH && react-deploy list $TRAVIS_BRANCH && react-deploy activate $RELEASE_HEAD $TRAVIS_BRANCH
  on:
    branch: "master"